import React,{useState}from"react";import{createRoot}from"react-dom/client";
import{Leaf,LayoutDashboard,Database,Plus,Cloud,Activity,Sparkles,Play,ShieldCheck,Bell,Settings,LogOut,Search,Clock3,Check,Wallet,Target,Eye,ArrowRight,RefreshCw,AlertTriangle,X,CircleCheck}from"lucide-react";
import{ResponsiveContainer,AreaChart,Area,XAxis,YAxis,Tooltip,CartesianGrid}from"recharts";import"./index.css";

// Chart colors mirror the tokens in index.css :root — keep the two in sync.
const T={brand:"#0c7c06",brandText:"#34AC2D",grid:"#26352b",axis:"#718078",surface:"#0d1712",line:"#304236",text:"#EDF3F7"};

const R=[["Telangana","India","Southern India (IN-SO)","INR","356"],["Gujarat","India","Western India (IN-WE)","INR","332"],["Himachal Pradesh","India","Northern India (IN-NO)","INR","218"],["West Bengal","India","Eastern India (IN-EA)","INR","438"],["California","United States","California","USD","205"],["South Australia","Australia","South Australia","AUD","290"]];
const C=[{h:"00",v:420},{h:"02",v:395},{h:"04",v:410},{h:"06",v:470},{h:"08",v:520},{h:"10",v:390},{h:"12",v:310},{h:"14",v:285},{h:"16",v:330},{h:"18",v:500},{h:"20",v:555},{h:"22",v:450}];
const seed=[["J1001","Fraud Detection Model Training","ML Engineer","ML Research","High","Scheduled","Sep 04, 16:00","Telangana","4h"],["J1002","Customer Data ETL","Data Engineer","Data Engineering","Medium","Running","Sep 04, 14:00","Telangana","2h"],["J1003","Marketing Analytics Job","Data Analyst","Analytics","Low","Pending","Sep 04, 20:00","Gujarat","3h"],["J1004","Nightly Database Backup","DevOps Engineer","Platform Ops","Low","Scheduled","Sep 05, 06:00","Telangana","2h"],["J1005","Weekly Business Report","Manager","Finance","Medium","Completed","Sep 04, 12:00","Telangana","1h"],["J1006","Release Build & Test","Developer","Application Dev","High","Scheduled","Sep 04, 18:00","Telangana","1.5h"]];

function App(){let[login,setLogin]=useState(false),[p,setP]=useState("Overview"),[reg,setReg]=useState(R[0]),[jobs,setJobs]=useState(seed),[sel,setSel]=useState(seed[0]),[q,setQ]=useState(""),[toast,setToast]=useState("");const go=x=>setP(x),msg=x=>{setToast(x);setTimeout(()=>setToast(""),2200)};if(!login)return <Login onLogin={()=>setLogin(true)}/>;
return <div className="app"><Side p={p} go={go} logout={()=>setLogin(false)}/><main><header><div><small>GreenShift / {p}</small><h1>{p}</h1></div><div className="headRight"><select value={reg[0]} onChange={e=>setReg(R.find(x=>x[0]==e.target.value))}>{R.map(x=><option key={x[0]}>{x[0]}</option>)}</select><button className="icon" onClick={()=>msg("No new critical notifications")}><Bell size={17}/><i/></button></div></header><section className="content">
{p=="Overview"&&<Overview jobs={jobs} go={go}/>}
{p=="Jobs"&&<Jobs jobs={jobs.filter(j=>(j.join(" ")).toLowerCase().includes(q.toLowerCase()))}q={q}setQ={setQ}newJob={()=>go("Submit Job")}open={j=>{setSel(j);go("Decision Explanation")}}/>}
{p=="Submit Job"&&<Submit reg={reg} done={j=>{setJobs([j,...jobs]);setSel(j);go("Decision Explanation");msg("Job submitted")}}/>}
{p=="Region Selection"&&<Region reg={reg}setReg={setReg}go={go}/>}
{p=="Carbon & Cost"&&<Carbon reg={reg}/>}
{p=="Decision Explanation"&&<Decision job={sel}go={go}msg={msg}/>}
{p=="Baseline Comparison"&&<Baseline job={sel}/>}
{p=="Job Monitoring"&&<Monitor jobs={jobs}/>}
{p=="Audit & Trust"&&<Audit/>}{p=="Alerts"&&<Alerts msg={msg}/>}</section></main>{toast&&<div className="toast"><CircleCheck size={17}/>{toast}</div>}</div>}

function Login({onLogin}){return <div className="login"><div className="hero"><div className="brand"><b>⌁</b> GreenShift</div><div className="heroText"><small>ENTERPRISE SUSTAINABILITY PLATFORM</small><h1>Carbon & cost-aware scheduling for deferrable compute.</h1><p>Shift flexible workloads to better execution windows while respecting deadlines, SLA, resources and carbon budgets.</p></div></div><div className="signin"><div className="box"><div className="brand"><b>⌁</b> GreenShift</div><h2>Welcome back</h2><p>Sign in to manage your enterprise workloads.</p><label>Email</label><input defaultValue="admin@company.com"/><label>Password</label><input type="password" defaultValue="greenshift"/><button className="primary full" onClick={onLogin}>Sign in <ArrowRight size={16}/></button><small>Demo environment • Enterprise Admin</small></div></div></div>}
function Side({p,go,logout}){let a=[["Overview",LayoutDashboard],["Jobs",Database],["Submit Job",Plus],["Region Selection",Cloud],["Carbon & Cost",Leaf],["Decision Explanation",Sparkles],["Baseline Comparison",Activity],["Job Monitoring",Play],["Audit & Trust",ShieldCheck],["Alerts",Bell]];return <aside><div className="brand"><b>⌁</b> GreenShift</div><small className="caption">CARBON-AWARE COMPUTE</small>{a.map(([x,I])=><button className={"nav "+(p==x?"on":"")} onClick={()=>go(x)} key={x}><I size={16}/>{x}</button>)}<div className="bottom"><button className="nav"><Settings size={16}/>Settings</button><div className="user"><span>PS</span><div><b>Priya N.</b><small>Platform Admin</small></div><button onClick={logout}><LogOut size={14}/></button></div></div></aside>}
function Top({title,sub,action}){return <div className="top"><div><h2>{title}</h2><p>{sub}</p></div>{action}</div>}
function K({icon:I,t,v,s}){return <div className="k"><span>{t}<I size={15}/></span><b>{v}</b><small>{s}</small></div>}
function Panel({t,children}){return <div className="panel"><h3>{t}</h3>{children}</div>}
function Chart(){return <ResponsiveContainer width="100%" height={250}><AreaChart data={C}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={T.brandText} stopOpacity=".38"/><stop offset="1" stopColor={T.brandText} stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke={T.grid} strokeDasharray="3 3"/><XAxis dataKey="h" stroke={T.axis} tick={{fontSize:13,fill:T.axis}}/><YAxis stroke={T.axis} tick={{fontSize:13,fill:T.axis}}/><Tooltip contentStyle={{background:T.surface,border:"1px solid "+T.line,borderRadius:8,color:T.text,fontSize:13}} labelStyle={{color:T.axis}} cursor={{stroke:T.brandText}}/><Area dataKey="v" stroke={T.brandText} fill="url(#g)" strokeWidth="2.5"/></AreaChart></ResponsiveContainer>}
function Overview({jobs,go}){return <><Top title="Overview" sub="Here’s what’s happening with your workloads today." action={<button className="primary" onClick={()=>go("Submit Job")}><Plus size={16}/> New Job</button>}/><div className="cards">{[[Database,"Total Jobs",jobs.length,"+8 this week"],[Clock3,"Scheduled",jobs.filter(x=>x[5]=="Scheduled").length,"Within SLA"],[Play,"Running",jobs.filter(x=>x[5]=="Running").length,"Active now"],[Check,"Completed",jobs.filter(x=>x[5]=="Completed").length,"Successful"],[Leaf,"Carbon Avoided","48.6 kg","CO₂e"],[Wallet,"Cost Saved","₹3,250","+11% vs baseline"],[Target,"Carbon Reduction","18.4%","Average"],[ShieldCheck,"SLA Compliance","98%","On time"]].map((x,i)=><K key={i} icon={x[0]} t={x[1]} v={x[2]} s={x[3]}/>)}</div><div className="grid"><Panel t="Carbon Intensity Trend"><Chart/></Panel><Panel t="Jobs by Status"><div className="donut"><div><b>{jobs.length}</b><small>Total</small></div></div><div className="legend">{[["Scheduled","a"],["Running","b"],["Pending","c"],["Completed","d"]].map(([label,tone])=><span className="lg" key={label}><i className={"dot "+tone}/>{label}<b>{jobs.filter(x=>x[5]==label).length}</b></span>)}</div></Panel></div><div className="grid"><Panel t="Upcoming Deadlines">{jobs.filter(x=>x[5]!="Completed").slice(0,4).map(j=><div className="deadline" key={j[0]}><Clock3 size={16}/><div><b>{j[1]}</b><small>{j[0]} • {j[3]}</small></div><span>{j[6]}</span></div>)}</Panel><Panel t="Carbon vs Cost Impact"><div className="impact"><b>Carbon avoided</b><strong>48.6 kg CO₂e</strong><b>Cost saved</b><strong>₹3,250</strong><div className="bar"><i/></div><small>GreenShift selects feasible windows with lower combined carbon and energy cost.</small></div></Panel></div></>}
function Jobs({jobs,q,setQ,newJob,open}){return <><Top title="Workloads" sub="Manage and monitor your deferrable compute workloads." action={<button className="primary" onClick={newJob}><Plus size={16}/> New Job</button>}/><div className="toolbar"><div className="search"><Search size={16}/><input placeholder="Search jobs, teams, requesters..." value={q} onChange={e=>setQ(e.target.value)}/></div><select><option>All Status</option></select><select><option>All Priorities</option></select></div><div className="table"><table><thead><tr><th>Job ID</th><th>Job Name</th><th>Requester</th><th>Team</th><th>Priority</th><th>Status</th><th>Deadline</th><th>Region</th><th/></tr></thead><tbody>{jobs.map(j=><tr key={j[0]}><td className="mono">{j[0]}</td><td><b>{j[1]}</b><small>{j[8]} runtime</small></td><td>{j[2]}</td><td>{j[3]}</td><td><em className={"pill "+j[4].toLowerCase()}>{j[4]}</em></td><td><span className="status">● {j[5]}</span></td><td>{j[6]}</td><td>{j[7]}</td><td><button className="link" onClick={()=>open(j)}><Eye size={14}/> View</button></td></tr>)}</tbody></table></div></>}
function Submit({reg,done}){let[f,setF]=useState({name:"",type:"ML Training",requester:"ML Engineer",team:"ML Research",priority:"Medium",duration:2,cpu:4,ram:16,gpu:1,deadline:"",carbon:2.5});let s=(k,v)=>setF({...f,[k]:v});return <><Top title="Submit New Job" sub="Provide workload requirements. GreenShift will find a feasible execution window."/><div className="formgrid"><Panel t="Job Details"><div className="fields"><Field t="Job name"><input value={f.name} onChange={e=>s("name",e.target.value)} placeholder="e.g. Fraud Detection Model Training"/></Field><Field t="Job type"><select value={f.type} onChange={e=>s("type",e.target.value)}>{["ML Training","ETL / Data Processing","Data Analytics","Backup","Report Generation","CI/CD"].map(x=><option>{x}</option>)}</select></Field><Field t="Requester role"><select value={f.requester} onChange={e=>s("requester",e.target.value)}>{["Developer","ML Engineer","Data Engineer","Data Analyst","DevOps Engineer","Manager"].map(x=><option>{x}</option>)}</select></Field><Field t="Team"><input value={f.team} onChange={e=>s("team",e.target.value)}/></Field><Field t="Priority"><select value={f.priority} onChange={e=>s("priority",e.target.value)}>{["Low","Medium","High","Critical"].map(x=><option>{x}</option>)}</select></Field><Field t="Estimated duration"><input type="number" value={f.duration} onChange={e=>s("duration",e.target.value)}/></Field></div></Panel><Panel t="Resource Requirements"><div className="fields"><Field t="CPU (cores)"><input type="number" value={f.cpu} onChange={e=>s("cpu",e.target.value)}/></Field><Field t="RAM (GB)"><input type="number" value={f.ram} onChange={e=>s("ram",e.target.value)}/></Field><Field t="GPU"><input type="number" value={f.gpu} onChange={e=>s("gpu",e.target.value)}/></Field><Field t="Replicas / Pods"><input type="number" defaultValue="1"/></Field></div></Panel><Panel t="Scheduling Constraints"><div className="fields"><Field t="Deadline"><input type="datetime-local" value={f.deadline} onChange={e=>s("deadline",e.target.value)}/></Field><Field t="SLA"><select><option>Standard</option><option>Gold</option><option>Critical</option></select></Field><Field t="Carbon budget (kg CO₂e)"><input value={f.carbon} onChange={e=>s("carbon",e.target.value)}/></Field><Field t="Preferred time"><input type="time"/></Field></div><label className="check"><input type="checkbox" defaultChecked/> Workload is deferrable</label></Panel></div><div className="submitbar">Region: <b>{reg[0]}</b><button className="primary" onClick={()=>done(["J"+(1007+Math.floor(Math.random()*90)),f.name||"New Workload",f.requester,f.team,f.priority,"Pending","Sep 05, 18:00",reg[0],f.duration+"h"])}>Submit Job & Find Green Slot <ArrowRight size={16}/></button></div></>}
function Field({t,children}){return <label><span>{t}</span>{children}</label>}
function Region({reg,setReg,go}){return <><Top title="Select Execution Region" sub="Choose where GreenShift should evaluate the workload."/><div className="regions">{R.map(r=><button className={reg[0]==r[0]?"region selected":"region"} onClick={()=>setReg(r)}><Cloud size={18}/><div><b>{r[0]}</b><small>{r[1]} • {r[2]}</small></div>{reg[0]==r[0]&&<Check/>}</button>)}</div><Panel t="Selected Region"><div className="details">{[["Region",reg[0]],["Country",reg[1]],["Timezone",reg[0]=="California"?"America/Los_Angeles":"Asia/Kolkata"],["Currency",reg[3]],["Tariff plan",reg[0]=="Telangana"?"HT-I(A) modeled ToD":"Configurable tariff"],["Current carbon",reg[4]+" gCO₂e/kWh"]].map(x=><div><small>{x[0]}</small><b>{x[1]}</b></div>)}</div><button className="primary" onClick={()=>go("Carbon & Cost")}>View Carbon & Cost <ArrowRight size={16}/></button></Panel></>}
function Carbon({reg}){return <><Top title="Carbon & Cost Information" sub={"Current and upcoming conditions for "+reg[0]+"."}/><div className="cards four">{[[Leaf,"Current carbon",reg[4]+" g","gCO₂e/kWh"],[Cloud,"Forecast low","285 g","14:00 local"],[Wallet,"Electricity price","₹7.65","modeled"],[Clock3,"Cheapest upcoming","22:00","ToD +₹0/unit"]].map((x,i)=><K key={i} icon={x[0]} t={x[1]} v={x[2]} s={x[3]}/>)}</div><div className="grid"><Panel t="Carbon Trend"><Chart/></Panel><Panel t="Tariff Windows"><div className="tariff"><b>06:00–10:00 <span>Peak +₹1/unit</span></b><b>10:00–18:00 <i>Normal +₹0/unit</i></b><b>18:00–22:00 <span>Peak +₹1/unit</span></b><b>22:00–06:00 <i>Night +₹0/unit</i></b></div><p className="notice">Tariff values are effective-date and consumer-category dependent.</p></Panel></div></>}
function Decision({job,go,msg}){return <><Top title="Scheduling Decision" sub={"Explainable recommendation for "+job[1]+" ("+job[0]+")."} action={<button className="secondary" onClick={()=>go("Baseline Comparison")}>Compare with Baseline <ArrowRight size={15}/></button>}/><div className="decision"><Sparkles/><div><small>RECOMMENDED EXECUTION WINDOW</small><h2>12:00 PM – 1 6:00 PM</h2><p>Best feasible balance of carbon intensity, electricity cost and workload constraints.</p></div><div className="decisionStats"><b>310 g/kWh<small>Carbon</small></b><b>₹498<small>Estimated cost</small></b><b>1.24 kg<small>CO₂e</small></b></div></div><div className="grid"><Panel t="Why this slot?"><Reason t="Meets carbon budget"/><Reason t="Completes before deadline"/><Reason t="CPU / RAM / GPU resources available"/><Reason t="Avoids evening peak tariff"/><Reason t="Lower carbon intensity than baseline"/></Panel><Panel t="Decision Factors"><div className="factor">Carbon impact <i style={{width:"86%"}}/></div><div className="factor">Cost impact <i style={{width:"72%"}}/></div><div className="factor">Deadline feasibility <i style={{width:"100%"}}/></div></Panel></div><Panel t="Candidate Slot Comparison"><table><thead><tr><th>Window</th><th>Carbon</th><th>Cost</th><th>Status</th><th>Reason</th></tr></thead><tbody>{[["10:00–14:00",520,612,"Rejected","Carbon budget exceeded"],["11:00–15:00",402,544,"Feasible","Within constraints"],["12:00–16:00",310,498,"Recommended","Best carbon + cost balance"],["14:00–18:00",335,526,"Feasible","Low carbon"],["16:00–20:00",462,588,"Higher carbon","Evening peak overlap"]].map(x=><tr><td>{x[0]}</td><td>{x[1]} g/kWh</td><td>₹{x[2]}</td><td className={x[3]=="Recommended"?"greenText":x[3]=="Rejected"?"redText":""}>{x[3]}</td><td>{x[4]}</td></tr>)}</tbody></table></Panel><div className="actions"><button className="secondary" onClick={()=>go("Jobs")}>Back</button><button className="primary" onClick={()=>{msg("Schedule confirmed");go("Job Monitoring")}}>Confirm Schedule <Check size={16}/></button></div></>}
function Reason({t}){return <p className="reason"><Check size={15}/>{t}</p>}
function Baseline(){return <><Top title="Baseline vs GreenShift" sub="Impact comparison using the selected workload."/><div className="comparison"><div><small>BASELINE</small><h2>12:00–16:00</h2><p>462 g/kWh</p><p>₹588 estimated cost</p><p>1.85 kg CO₂e</p></div><ArrowRight/><div className="highlight"><small>GREENSHIFT • OPTIMIZED</small><h2>14:00–18:00</h2><p>310 g/kWh</p><p>₹498 estimated cost</p><p>1.24 kg CO₂e</p></div></div><div className="cards three"><K icon={Leaf} t="Carbon avoided" v="0.61 kg" s="33% reduction"/><K icon={Wallet} t="Cost saved" v="₹90" s="15.3% reduction"/><K icon={ShieldCheck} t="SLA impact" v="None" s="Deadline preserved"/></div><Panel t="Methodology"><p className="method">Baseline uses the default/earliest feasible execution window. GreenShift evaluates feasible windows using carbon intensity, configured tariff, runtime, deadline, SLA and resource constraints.</p></Panel></>}
function Monitor({jobs}){let[j,setJ]=useState(jobs[0]);return <><Top title="Job Monitoring" sub="Track scheduled, running and completed workloads." action={<button className="secondary"><RefreshCw size={15}/> Refresh</button>}/><div className="monitor"><div>{jobs.map(x=><button className={j[0]==x[0]?"mrow sel":"mrow"} onClick={()=>setJ(x)}><span>●</span><div><b>{x[1]}</b><small>{x[0]} • {x[3]}</small></div><em>{x[5]}</em></button>)}</div><Panel t="Execution Details"><h2 className="jobtitle">{j[1]}</h2><p>{j[0]} • {j[2]} • {j[7]}</p><div className="progress"><span>Execution progress</span><b>{j[5]=="Completed"?"100%":j[5]=="Running"?"58%":"0%"}</b><i style={{width:j[5]=="Completed"?"100%":j[5]=="Running"?"58%":"0%"}}/></div><div className="details three">{[["Scheduled start",j[6]],["Runtime",j[8]],["Deadline",j[6]],["Status",j[5]],["Priority",j[4]],["Region",j[7]]].map(x=><div><small>{x[0]}</small><b>{x[1]}</b></div>)}</div><div className="timeline"><b>✓ Job accepted</b><b>✓ Schedule decided</b><b>● Execution</b><b>○ Completion</b></div></Panel></div></>}
function Audit(){let rows=[["J1001","Submitted","11:03:12","Job Registry"],["J1001","Constraints validated","11:03:13","Eligibility Agent"],["J1001","Carbon signal fetched","11:03:14","Carbon Service"],["J1001","Tariff version FY26-27","11:03:14","Tariff Service"],["J1001","Candidate windows scored","11:03:15","Decide Agent"],["J1001","12:00–16:00 selected","11:03:15","Scheduler"],["J1001","Dispatch request created","11:03:16","Dispatch Agent"]];return <><Top title="Audit & Trust" sub="Tamper-evident decision history for GreenShift scheduling." action={<span className="verified"><ShieldCheck size={15}/> Hash chain verified</span>}/><div className="cards three"><K icon={ShieldCheck} t="Verified events" v="7 / 7" s="No breaks detected"/><K icon={Database} t="Audited jobs" v="128" s="100% coverage"/><K icon={Activity} t="Latest record" v="11:03:16" s="Today"/></div><Panel t="Decision Audit Trail"><table><thead><tr><th>Job</th><th>Event</th><th>Timestamp</th><th>Service</th><th>Integrity</th></tr></thead><tbody>{rows.map(x=><tr><td>{x[0]}</td><td>{x[1]}</td><td>{x[2]}</td><td>{x[3]}</td><td className="greenText">✓ Verified</td></tr>)}</tbody></table></Panel><div className="notice big"><ShieldCheck/> <span><b>What is stored?</b><br/>Job constraints, signal timestamps, tariff version, candidate scores, selected slot, decision reason and dispatch events. Each record is chained to the previous record hash.</span></div></>}
function Alerts({msg}){let a=[["Deadline risk","J1003 is approaching its deadline. Review the recommended window.","High"],["Tariff data check","FY26-27 Telangana ToD configuration is active.","Info"],["Carbon signal healthy","Southern India carbon signal was refreshed recently.","Healthy"],["SLA preserved","All scheduled jobs remain within their declared SLA.","Healthy"]];return <><Top title="Alerts & Notifications" sub="Operational events that may require attention." action={<button className="secondary" onClick={()=>msg("All alerts reviewed")}><Check size={15}/> Mark reviewed</button>}/><div className="alerts">{a.map((x,i)=><div className={"alert "+(i==0?"danger":"")}><AlertTriangle size={18}/><div><b>{x[0]}</b><p>{x[1]}</p><small>Today • GreenShift monitoring</small></div><em>{x[2]}</em><X size={15}/></div>)}</div><Panel t="Notification Rules">{["Deadline risk within 2 hours","Carbon signal unavailable or stale","Tariff configuration expires","SLA breach detected","No feasible green slot"].map((x,i)=><div className="rule"><b>{x}<small>Notify Platform Admin</small></b><input type="checkbox" defaultChecked={i<4}/></div>)}</Panel></>}
createRoot(document.getElementById("root")).render(<App/>);